# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76e762f082b5572b303d231f79bf53ae7f2b0aa2af8d7f25e59eaddebd8e2b4bedfef0dcf9021f936336e61a08969af34b4bfc2db4d5fc837e4f50190981e864

test:
  secret_key_base: 1ca7d530b8ee5c49ac929d18568e1c38ae639f8bbcf3c4ed7fb03a988854452b2a87570f9e3d2b497783d1356d052ef6d3b4b80cf44a2faed26ed27249a3876b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
